services:
  postgres:
    image: postgis/postgis:16-3.4 #Postgis For Geolocalisation
    container_name: kayrros-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-kayrros_hotspots}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data #Data of persistance
      - ./db/schema:/docker-entrypoint-initdb.d #Init of live schema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-kayrros_hotspots}"] #Verifiy health check
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kayrros-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kayrros-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-kayrros_hotspots}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app/api
      - ./utils:/app/utils
      - ./static:/app/static
      - ./logs:/app/logs  # ensure logs are visible on host

    networks:
      - kayrros-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  kayrros-network:
    driver: bridge

