name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest #define VM

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 #pulls repo into VM

    - name: Set up Python
      uses: actions/setup-python@v4 #sets up Python 3.9
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest black

    - name: Run tests with pytest
      run: |
        PYTHONPATH=$PYTHONPATH:. pytest tests/

   

    - name: Check code formatting with black
      run: black --check app app tests ingestion
    #black app app tests ingestion